# Generated by Django 5.2.4 on 2025-07-08 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelamBusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(default='selam_bus', max_length=200)),
                ('starting_point', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_by_km', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('plate_number', models.BigIntegerField()),
                ('bus_image', models.ImageField(upload_to='bus_image')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTickect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.ImageField(upload_to='payment_methods')),
                ('digital_id', models.ImageField(upload_to='user digital id')),
                ('bocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selam_ticket.selambusinfo')),
            ],
        ),
    ]
