# Generated by Django 5.2.4 on 2025-07-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selam_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selambusinfo',
            name='max_volume',
            field=models.SmallIntegerField(default=50),
        ),
    ]
