# Generated by Django 5.2.4 on 2025-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selam_ticket', '0002_selambusinfo_max_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='announcement')),
                ('Description', models.TextField()),
            ],
        ),
    ]
