# Generated by Django 5.2.4 on 2025-07-11 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selam_ticket', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='About',
            field=models.CharField(default='did not define', max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
