# Generated by Django 5.2.4 on 2025-07-11 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selam_ticket', '0004_announcement_about_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='selambusinfo',
            name='TravelAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
